# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    # Generates CLAUDE.md optimized for Claude Code.
    # In :compact mode (default), produces ≤150 lines with MCP tool references.
    # In :full mode, delegates to MarkdownSerializer with behavioral rules.
    class ClaudeSerializer
      attr_reader :context

      def initialize(context)
        @context = context
      end

      def call
        if RailsAiBridge.configuration.context_mode == :full
          FullClaudeSerializer.new(context).call
        else
          render_compact
        end
      end

      private

      def render_compact
        lines = []
        lines.concat(render_header)
        lines.concat(render_stack_overview)
        lines.concat(render_key_models)
        lines.concat(render_notable_gems)
        lines.concat(render_architecture)
        lines.concat(render_performance_security_baseline)
        lines.concat(render_mcp_guide)
        lines.concat(render_conventions)
        lines.concat(render_commands)
        lines.concat(render_footer)

        # Enforce max lines
        max = RailsAiBridge.configuration.claude_max_lines
        if lines.size > max
          lines = lines.first(max - 2)
          lines << ""
          lines << "_Context trimmed. Use MCP tools for full details._"
        end

        lines.join("\n")
      end

      def render_header
        [
          "# #{context[:app_name]} — AI Context",
          "",
          "> Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}",
          "> Generated by rails-ai-bridge v#{RailsAiBridge::VERSION}",
          ""
        ]
      end

      def render_stack_overview
        lines = [ "## Stack" ]

        schema = context[:schema]
        if schema && !schema[:error]
          lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables"
        end

        models = context[:models]
        if models.is_a?(Hash) && !models[:error]
          lines << "- Models: #{models.size}"
        end

        line = ContextSummary.routes_stack_line(context)
        lines << line if line

        auth = context[:auth]
        if auth.is_a?(Hash) && !auth[:error]
          parts = []
          parts << "Devise" if auth.dig(:authentication, :devise)&.any?
          parts << "Rails 8 auth" if auth.dig(:authentication, :rails_auth)
          parts << "Pundit" if auth.dig(:authorization, :pundit)&.any?
          parts << "CanCanCan" if auth.dig(:authorization, :cancancan)
          lines << "- Auth: #{parts.join(' + ')}" if parts.any?
        end

        jobs = context[:jobs]
        if jobs.is_a?(Hash) && !jobs[:error]
          job_count = jobs[:jobs]&.size || 0
          mailer_count = jobs[:mailers]&.size || 0
          channel_count = jobs[:channels]&.size || 0
          parts = []
          parts << "#{job_count} jobs" if job_count > 0
          parts << "#{mailer_count} mailers" if mailer_count > 0
          parts << "#{channel_count} channels" if channel_count > 0
          lines << "- Async: #{parts.join(', ')}" if parts.any?
        end

        migrations = context[:migrations]
        if migrations.is_a?(Hash) && !migrations[:error]
          pending = migrations[:pending]
          lines << "- Migrations: #{migrations[:total]} total, #{pending&.size || 0} pending"
        end

        lines << ""
        lines
      end

      def render_key_models
        models = context[:models]
        return [] unless models.is_a?(Hash) && !models[:error] && models.any?

        schema_tables = context.dig(:schema, :tables) || {}
        migrations    = context[:migrations]
        max_show = 15

        lines = [ "## Key models (#{models.size} total)" ]
        sorted_names = models.sort_by { |_name, data| -ContextSummary.model_complexity_score(data) }.map(&:first)
        sorted_names.first(max_show).each do |name|
          data = models[name]
          assoc_count = (data[:associations] || []).size
          val_count   = (data[:validations] || []).size
          enum_names  = (data[:enums] || {}).keys
          top_assocs  = (data[:associations] || []).first(3).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          table_name  = data[:table_name]

          line = "- **#{name}**"
          line += " (#{assoc_count}a, #{val_count}v)" if assoc_count > 0 || val_count > 0
          line += " [enums: #{enum_names.join(', ')}]" if enum_names.any?

          cols = ContextSummary.top_columns(schema_tables[table_name])
          line += " [cols: #{cols.map { |c| "#{c[:name]}:#{c[:type]}" }.join(', ')}]" if cols.any?

          line += " [recently migrated]" if table_name && ContextSummary.recently_migrated?(table_name, migrations)
          line += " — #{top_assocs}" if top_assocs && !top_assocs.empty?
          lines << line
        end
        lines << "- _...#{models.size - max_show} more (use `rails_get_model_details` tool)_" if models.size > max_show
        lines << ""
        lines
      end

      def render_notable_gems
        gems = context[:gems]
        return [] unless gems.is_a?(Hash) && !gems[:error]
        notable = gems[:notable_gems] || gems[:notable] || gems[:detected] || []
        return [] if notable.empty?

        lines = [ "## Gems" ]
        grouped = notable.group_by { |g| g[:category]&.to_s || "other" }
        grouped.each do |category, gem_list|
          names = gem_list.map { |g| g[:name] }.join(", ")
          lines << "- **#{category}**: #{names}"
        end
        lines << ""
        lines
      end

      def render_architecture
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        arch = conv[:architecture] || []
        patterns = conv[:patterns] || []
        return [] if arch.empty? && patterns.empty?

        lines = [ "## Architecture" ]
        arch.each { |p| lines << "- #{p}" }
        patterns.first(8).each { |p| lines << "- #{p}" }
        lines << ""
        lines
      end

      def render_performance_security_baseline
        ContextSummary.compact_performance_security_section + [ "" ]
      end

      def render_mcp_guide # rubocop:disable Metrics/MethodLength
        [
          "## MCP Tool Reference",
          "",
          "This project exposes live MCP tools. **Always start with `detail:\"summary\"`**,",
          "then drill into specifics with a filter or `detail:\"full\"`.",
          "",
          "### Detail levels (schema, routes, models, controllers)",
          "",
          "| Level | Returns | Default limit |",
          "|-------|---------|---------------|",
          "| `summary` | Names + counts | 50 |",
          "| `standard` | Names + key details | 15 (default) |",
          "| `full` | Everything (indexes, FKs, etc.) | 5 |",
          "",
          "### rails_get_schema",
          "Params: `table`, `detail`, `limit`, `offset`, `format`",
          "- `rails_get_schema(detail:\"summary\")` — all tables with column counts",
          "- `rails_get_schema(table:\"users\")` — full detail for one table",
          "- `rails_get_schema(detail:\"summary\", limit:20, offset:40)` — paginate",
          "",
          "### rails_get_model_details",
          "Params: `model`, `detail`",
          "- `rails_get_model_details(detail:\"summary\")` — list all model names",
          "- `rails_get_model_details(model:\"User\")` — associations, validations, scopes, enums, callbacks",
          "- `rails_get_model_details(detail:\"full\")` — all models with full association lists",
          "",
          "### rails_get_routes",
          "Params: `controller`, `detail`, `limit`, `offset`",
          "- `rails_get_routes(detail:\"summary\")` — route counts per controller",
          "- `rails_get_routes(controller:\"users\")` — routes for one controller",
          "- `rails_get_routes(detail:\"full\", limit:50)` — full table with route names",
          "",
          "### rails_get_controllers",
          "Params: `controller`, `detail`",
          "- `rails_get_controllers(detail:\"summary\")` — names + action counts",
          "- `rails_get_controllers(controller:\"UsersController\")` — actions, filters, strong params",
          "",
          "### Other tools (no detail param)",
          "- `rails_get_config` — cache store, session, timezone, middleware, initializers",
          "- `rails_get_test_info` — test framework, factories/fixtures, CI config, coverage",
          "- `rails_get_gems` — notable gems categorized by function (auth, background jobs, etc.)",
          "- `rails_get_conventions` — architecture patterns, directory structure, config files",
          "- `rails_search_code(pattern:\"regex\", file_type:\"rb\", max_results:20)` — ripgrep search",
          ""
        ]
      end

      def render_conventions
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        config_files = conv[:config_files] || []
        return [] if config_files.empty?

        lines = [ "## Key config files" ]
        config_files.first(5).each { |f| lines << "- `#{f}`" }
        lines << ""
        lines
      end

      def render_commands
        [
          "## Commands",
          "- `bin/dev` — start dev server",
          "- `#{ContextSummary.test_command(context)}` — run tests",
          "- `rails db:migrate` — run pending migrations",
          ""
        ]
      end

      def render_footer
        [
          "## Rules",
          "- Follow existing patterns and conventions",
          "- Use the MCP tools to check schema before writing migrations",
          "- Match existing code style",
          "- Run tests after changes",
          ""
        ]
      end
    end

    # Internal: full-mode Claude serializer (wraps MarkdownSerializer with behavioral rules)
    class FullClaudeSerializer < MarkdownSerializer
      private

      def header
        <<~MD
          # #{context[:app_name]} — AI Context

          > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives Claude Code deep context about this Rails application's
          structure, patterns, and conventions. Use it to write idiomatic code
          that matches this project's style.
        MD
      end

      def footer
        rules = []
        rules << "## Behavioral Rules"
        rules << ""
        rules << "When working in this codebase:"
        rules << "- Follow existing patterns and conventions detected above"
        rules << "- Use the database schema as the source of truth for column names and types"
        rules << "- Respect existing associations and validations when modifying models"
        rules << "- Match the project's architecture style (#{architecture_summary})" if architecture_summary
        rules << "- Run `#{ContextSummary.test_command(context)}` after making changes to verify correctness"
        rules << ""
        rules << super
        rules.join("\n")
      end

      def architecture_summary
        arch = context.dig(:conventions, :architecture)
        arch&.any? ? arch.join(", ") : nil
      end
    end
  end
end
