# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    # Builds shared markdown headers for provider context files (full-mode Markdown output).
    module ProviderDocumentHeader
      module_function

      # Renders a document header with title, metadata lines, and intro body.
      #
      # @param context [Hash] must include +:app_name+, +:rails_version+, +:ruby_version+; +:generated_at+ required when +layout+ is +:ai_context+
      # @param document_title [String] text after em dash (e.g. +"AI Context"+, +"Copilot Instructions"+)
      # @param intro [String] one or more paragraphs (no leading blank line)
      # @param layout [Symbol] +:ai_context+ (generator block first) or +:instructions+ (Rails/Ruby line first)
      # @return [String]
      # @raise [ArgumentError] if +layout+ is unknown
      def call(context:, document_title:, intro:, layout:)
        app = context[:app_name]
        rails_v = context[:rails_version]
        ruby_v = context[:ruby_version]
        version = RailsAiBridge::VERSION

        meta_lines =
          case layout
          when :ai_context
            generated = context[:generated_at]
            [
              "> Auto-generated by rails-ai-bridge v#{version}",
              "> Generated: #{generated}",
              "> Rails #{rails_v} | Ruby #{ruby_v}"
            ]
          when :instructions
            [
              "> Rails #{rails_v} | Ruby #{ruby_v}",
              "> Auto-generated by rails-ai-bridge v#{version}"
            ]
          else
            raise ArgumentError, "unknown header layout: #{layout.inspect}"
          end

        <<~MD
          # #{app} — #{document_title}

          #{meta_lines.join("\n")}

          #{intro.rstrip}
        MD
      end

      # Minimal header for +.cursorrules+ full-mode project rules (no blockquote metadata).
      #
      # @param context [Hash] +:app_name+, +:rails_version+, +:ruby_version+
      # @return [String]
      def rules_banner(context:)
        <<~MD
          # #{context[:app_name]} — Project Rules

          Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
        MD
      end
    end
  end
end
