# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    # Builds the standard `---` regeneration footer used across provider context files.
    module RegenerationFooter
      module_function

      # Renders the italic regeneration line for a rake command.
      #
      # @param command [String] shell command (e.g. +rails ai:bridge+)
      # @param variant [Symbol] +:context_file+, +:auto_short+, or +:auto_branded+
      # @return [String] single markdown line (italic wrapper)
      # @raise [ArgumentError] if +variant+ is unknown
      def message_line(command:, variant:)
        case variant
        when :context_file
          "_This context file is auto-generated. Run `#{command}` to regenerate._"
        when :auto_short
          "_Auto-generated. Run `#{command}` to regenerate._"
        when :auto_branded
          "_Auto-generated by rails-ai-bridge. Run `#{command}` to regenerate._"
        else
          raise ArgumentError, "unknown regeneration footer variant: #{variant.inspect}"
        end
      end

      # Full markdown block: horizontal rule plus regeneration line (trailing newline).
      #
      # @param command [String]
      # @param variant [Symbol]
      # @return [String]
      def markdown(command:, variant:)
        <<~MD
          ---
          #{message_line(command: command, variant: variant)}
        MD
      end

      # Lines to append after body content: blank line, rule, regeneration line (no trailing newline on string).
      #
      # @param command [String]
      # @param variant [Symbol]
      # @return [Array<String>]
      def continuation_lines(command:, variant:)
        ['', '---', message_line(command: command, variant: variant)]
      end
    end
  end
end
