# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    module Formatters
      # Renders the Claude Code-specific document header.
      class ClaudeHeaderFormatter < Base
        # @return [String]
        def call
          <<~MD
            # #{context[:app_name]} — AI Context

            > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}
            > Generated: #{context[:generated_at]}
            > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

            This file gives Claude Code deep context about this Rails application's
            structure, patterns, and conventions. Use it to write idiomatic code
            that matches this project's style.
          MD
        end
      end
    end
  end
end
