# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    module Formatters
      # Renders the Codex (AGENTS.md) document header.
      class CodexHeaderFormatter < Base
        # @return [String]
        def call
          <<~MD
            # #{context[:app_name]} — Codex Instructions

            > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
            > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}

            Codex reads AGENTS.md before starting work. Use this file as the
            project-level instruction source for repository-specific guidance.
          MD
        end
      end
    end
  end
end
