# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    module Formatters
      # Renders the document header with app name, version, and generator metadata.
      class HeaderFormatter < Base
        # @return [String]
        def call
          <<~MD
            # #{context[:app_name]} — AI Context

            > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}
            > Generated: #{context[:generated_at]}
            > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

            This file gives AI assistants (Claude Code, Cursor, Copilot) deep context
            about this Rails application's structure, patterns, and conventions.
          MD
        end
      end
    end
  end
end
