# frozen_string_literal: true

require 'spec_helper'

module RailsAiBridge
  module Serializers
    module Formatters::Providers
      RSpec.describe 'Formatter classes' do
        let(:header_ctx) do
          {
            app_name: 'MyApp',
            rails_version: '7.2.0',
            ruby_version: '3.3.0',
            generated_at: '2024-06-01T12:00:00Z'
          }
        end

        let(:footer_ctx) { { tests: { framework: 'rspec' } } }

        # ---------------------------------------------------------------------------
        # RulesHeaderFormatter
        # ---------------------------------------------------------------------------
        describe RulesHeaderFormatter do
          subject(:output) { described_class.new(header_ctx).call }

          it 'matches the project rules header template' do
            expect(output).to eq(<<~MD)
              # MyApp — Project Rules

              Rails 7.2.0 | Ruby 3.3.0
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # RulesFooterFormatter
        # ---------------------------------------------------------------------------
        describe RulesFooterFormatter do
          subject(:output) { described_class.new({}).call }

          it 'matches the rules footer regeneration block' do
            expect(output).to eq(<<~MD)
              ---
              _Auto-generated by rails-ai-bridge. Run `rails ai:bridge` to regenerate._
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # HeaderFormatter
        # ---------------------------------------------------------------------------
        describe HeaderFormatter do
          subject(:output) { described_class.new(header_ctx).call }

          it 'matches the default AI context header template' do
            expect(output).to eq(<<~MD)
              # MyApp — AI Context

              > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}
              > Generated: 2024-06-01T12:00:00Z
              > Rails 7.2.0 | Ruby 3.3.0

              This file gives AI assistants (Claude Code, Cursor, Copilot) deep context
              about this Rails application's structure, patterns, and conventions.
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # GeminiHeaderFormatter
        # ---------------------------------------------------------------------------
        describe GeminiHeaderFormatter do
          subject(:output) { described_class.new(header_ctx).call }

          it 'matches the Gemini-specific AI context header' do
            expect(output).to eq(<<~MD)
              # MyApp — AI Context

              > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}
              > Generated: 2024-06-01T12:00:00Z
              > Rails 7.2.0 | Ruby 3.3.0

              This file provides a high-level overview of this Rails application's
              structure, patterns, and conventions. As an AI assistant, use this context
              to quickly understand the project and generate idiomatic code that
              adheres to its design decisions. For deeper dives, use the live
              MCP tools referenced throughout this document.
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # ClaudeHeaderFormatter
        # ---------------------------------------------------------------------------
        describe ClaudeHeaderFormatter do
          subject(:output) { described_class.new(header_ctx).call }

          it 'matches the Claude Code AI context header' do
            expect(output).to eq(<<~MD)
              # MyApp — AI Context

              > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}
              > Generated: 2024-06-01T12:00:00Z
              > Rails 7.2.0 | Ruby 3.3.0

              This file gives Claude Code deep context about this Rails application's
              structure, patterns, and conventions. Use it to write idiomatic code
              that matches this project's style.
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # CopilotHeaderFormatter
        # ---------------------------------------------------------------------------
        describe CopilotHeaderFormatter do
          subject(:output) { described_class.new(header_ctx).call }

          it 'matches the Copilot instructions header layout' do
            expect(output).to eq(<<~MD)
              # MyApp — Copilot Instructions

              > Rails 7.2.0 | Ruby 3.3.0
              > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}

              Use this context to generate code that fits this project's structure and patterns.
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # CodexHeaderFormatter
        # ---------------------------------------------------------------------------
        describe CodexHeaderFormatter do
          subject(:output) { described_class.new(header_ctx).call }

          it 'matches the Codex AGENTS header layout' do
            expect(output).to eq(<<~MD)
              # MyApp — Codex Instructions

              > Rails 7.2.0 | Ruby 3.3.0
              > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}

              Codex reads AGENTS.md before starting work. Use this file as the
              project-level instruction source for repository-specific guidance.
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # FooterFormatter
        # ---------------------------------------------------------------------------
        describe FooterFormatter do
          subject(:output) { described_class.new({}).call }

          it 'matches the standard context file regeneration footer' do
            expect(output).to eq(<<~MD)
              ---
              _This context file is auto-generated. Run `rails ai:bridge` to regenerate._
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # CopilotFooterFormatter
        # ---------------------------------------------------------------------------
        describe CopilotFooterFormatter do
          subject(:output) { described_class.new({}).call }

          it 'matches the short Copilot regeneration footer' do
            expect(output).to eq(<<~MD)
              ---
              _Auto-generated. Run `rails ai:bridge` to regenerate._
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # CodexFooterFormatter
        # ---------------------------------------------------------------------------
        describe CodexFooterFormatter do
          subject(:output) { described_class.new({}).call }

          it 'matches the Codex-specific regeneration footer' do
            expect(output).to eq(<<~MD)
              ---
              _Auto-generated. Run `rails ai:bridge:codex` to regenerate._
            MD
          end
        end

        # ---------------------------------------------------------------------------
        # ClaudeFooterFormatter
        # ---------------------------------------------------------------------------
        describe ClaudeFooterFormatter do
          subject(:output) { described_class.new(footer_ctx).call }

          it 'matches the Claude behavioral rules footer without architecture hints' do
            expect(output).to eq(<<~MD.chomp)
              ## Behavioral Rules

              When working in this codebase:
              - Follow existing patterns and conventions detected above
              - Use the database schema as the source of truth for column names and types
              - Respect existing associations and validations when modifying models
              - Run `bundle exec rspec` after making changes to verify correctness

              ---
              _This context file is auto-generated. Run `rails ai:bridge` to regenerate._
            MD
          end

          it 'inserts an architecture line when conventions include architecture' do
            ctx = footer_ctx.merge(conventions: { architecture: %w[layered hexagonal] })
            md = described_class.new(ctx).call
            expect(md).to include("- Match the project's architecture style (layered, hexagonal)")
            expect(md).to include('Run `bundle exec rspec` after making changes')
          end
        end

        # ---------------------------------------------------------------------------
        # GeminiFooterFormatter
        # ---------------------------------------------------------------------------
        describe GeminiFooterFormatter do
          subject(:output) { described_class.new(footer_ctx).call }

          it 'uses the Behavioral Rules heading' do
            expect(output.lines.first.chomp).to eq('## Behavioral Rules')
          end

          it 'includes the same rule bullets and trailer as shared compact footer (with Gemini heading)' do
            shared_md = SharedAssistantGuidance.compact_engineering_rules_footer_lines(footer_ctx).join("\n")
            expect(output).to eq(shared_md.sub(/\A## Rules\n/, "## Behavioral Rules\n"))
          end

          it 'appends Match Architecture when conventions include architecture' do
            ctx = footer_ctx.merge(conventions: { architecture: %w[layered hexagonal] })
            md = described_class.new(ctx).call
            expect(md).to include(
              "- **Match Architecture:** Align with the project's architectural style (layered, hexagonal)."
            )
          end
        end

        # ---------------------------------------------------------------------------
        # McpGuideFormatter
        # ---------------------------------------------------------------------------
        describe McpGuideFormatter do
          subject(:output) { described_class.new({}).call }

          it 'matches the full compact MCP tool reference markdown' do
            expect(output).to eq(<<~MARKDOWN.rstrip)
              ## MCP Tool Reference

              This project exposes live MCP tools. **Always start with `detail:"summary"`**,
              then drill into specifics with a filter or `detail:"full"`.

              ### Detail levels (schema, routes, models, controllers)

              | Level | Returns | Default limit |
              |-------|---------|---------------|
              | `summary` | Names + counts | 50 |
              | `standard` | Names + key details | 15 (default) |
              | `full` | Everything (indexes, FKs, etc.) | 5 |

              ### rails_get_schema
              Params: `table`, `detail`, `limit`, `offset`, `format`
              - `rails_get_schema(detail:"summary")` — all tables with column counts
              - `rails_get_schema(table:"users")` — full detail for one table
              - `rails_get_schema(detail:"summary", limit:20, offset:40)` — paginate

              ### rails_get_model_details
              Params: `model`, `detail`
              - `rails_get_model_details(detail:"summary")` — list all model names
              - `rails_get_model_details(model:"User")` — associations, validations, scopes, enums, callbacks
              - `rails_get_model_details(detail:"full")` — all models with full association lists

              ### rails_get_routes
              Params: `controller`, `detail`, `limit`, `offset`
              - `rails_get_routes(detail:"summary")` — route counts per controller
              - `rails_get_routes(controller:"users")` — routes for one controller
              - `rails_get_routes(detail:"full", limit:50)` — full table with route names

              ### rails_get_controllers
              Params: `controller`, `detail`
              - `rails_get_controllers(detail:"summary")` — names + action counts
              - `rails_get_controllers(controller:"UsersController")` — actions, filters, strong params

              ### Other tools (no detail param)
              - `rails_get_config` — cache store, session, timezone, middleware, initializers
              - `rails_get_test_info` — test framework, factories/fixtures, CI config, coverage
              - `rails_get_gems` — notable gems categorized by function (auth, background jobs, etc.)
              - `rails_get_conventions` — architecture patterns, directory structure, config files
              - `rails_search_code(pattern:"regex", file_type:"rb", max_results:20)` — ripgrep search
            MARKDOWN
          end
        end
      end
    end
  end
end
