module RailsAiBridge
  module Serializers
    module Formatters::Providers
      RSpec.describe "Formatter classes" do
        # ---------------------------------------------------------------------------
        # RulesHeaderFormatter
        # ---------------------------------------------------------------------------
        describe RulesHeaderFormatter do
          let(:ctx) { { app_name: "MyApp", rails_version: "7.2.0", ruby_version: "3.3.0" } }

          subject(:output) { described_class.new(ctx).call }

          it "includes the app name" do
            expect(output).to include("MyApp")
          end

          it "includes Rails and Ruby versions" do
            expect(output).to include("Rails 7.2.0 | Ruby 3.3.0")
          end

          it "includes the header title" do
            expect(output).to include("Project Rules")
          end
        end

        # ---------------------------------------------------------------------------
        # RulesFooterFormatter
        # ---------------------------------------------------------------------------
        describe RulesFooterFormatter do
          subject(:output) { described_class.new({}).call }

          it "includes the auto-generated notice" do
            expect(output).to include("Auto-generated by rails-ai-bridge")
          end
        end

        # ---------------------------------------------------------------------------
        # HeaderFormatter
        # ---------------------------------------------------------------------------
        describe HeaderFormatter do
          let(:ctx) { { app_name: "MyApp", rails_version: "7.2.0", ruby_version: "3.3.0" } }

          subject(:output) { described_class.new(ctx).call }

          it "includes the app name" do
            expect(output).to include("MyApp")
          end

          it "includes Rails and Ruby versions" do
            expect(output).to include("Rails 7.2.0 | Ruby 3.3.0")
          end

          it "includes the header title" do
            expect(output).to include("AI Context")
          end
        end

        # ---------------------------------------------------------------------------
        # FooterFormatter
        # ---------------------------------------------------------------------------
        describe FooterFormatter do
          subject(:output) { described_class.new({}).call }

          it "includes the auto-generated notice" do
            expect(output).to include("rails ai:bridge")
          end
        end
      end
    end
  end
end
