# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    module Formatters::Providers
      # Renders the Copilot Instructions document header.
      class CopilotHeaderFormatter < Formatters::Base
        # @return [String]
        def call
          <<~MD
            # #{context[:app_name]} — Copilot Instructions

            > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
            > Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}

            Use this context to generate code that fits this project's structure and patterns.
          MD
        end
      end
    end
  end
end
