# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    module Formatters::Providers
      # Renders the project rules document footer for .cursorrules full mode.
      class RulesFooterFormatter < Base
        # @return [String]
        def call
          <<~MD
            ---
            _Auto-generated by rails-ai-bridge. Run `rails ai:bridge` to regenerate._
          MD
        end
      end
    end
  end
end
