# frozen_string_literal: true

require "spec_helper"

module RailsAiBridge
  module Serializers
    module Formatters
      RSpec.describe "Formatter classes" do
        # ---------------------------------------------------------------------------
        # RulesHeaderFormatter
        # ---------------------------------------------------------------------------
        describe RulesHeaderFormatter do
          let(:ctx) { { app_name: "MyApp", rails_version: "7.2.0", ruby_version: "3.3.0" } }

          subject(:output) { described_class.new(ctx).call }

          it "includes the app name" do
            expect(output).to include("MyApp")
          end

          it "includes Rails and Ruby versions" do
            expect(output).to include("Rails 7.2.0")
            expect(output).to include("Ruby 3.3.0")
          end

          it "uses the Project Rules heading" do
            expect(output).to include("Project Rules")
          end
        end

        # ---------------------------------------------------------------------------
        # RulesFooterFormatter
        # ---------------------------------------------------------------------------
        describe RulesFooterFormatter do
          subject(:output) { described_class.new({}).call }

          it "includes the auto-generated notice" do
            expect(output).to include("Auto-generated by rails-ai-bridge")
          end

          it "includes the regenerate command" do
            expect(output).to include("rails ai:bridge")
          end

          it "includes a horizontal rule" do
            expect(output).to include("---")
          end
        end

        # ---------------------------------------------------------------------------
        # AuthFormatter
        # ---------------------------------------------------------------------------
        describe AuthFormatter do
          it "returns nil when no auth key in context" do
            expect(described_class.new({}).call).to be_nil
          end

          it "returns nil when auth has an error" do
            expect(described_class.new({ auth: { error: "failed" } }).call).to be_nil
          end

          it "returns nil when authentication and authorization are both empty" do
            ctx = { auth: { authentication: {}, authorization: {} } }
            expect(described_class.new(ctx).call).to be_nil
          end

          it "renders Devise models" do
            ctx = {
              auth: {
                authentication: { devise: [ { model: "User", matches: [ "database_authenticatable" ] } ] },
                authorization: {}
              }
            }
            output = described_class.new(ctx).call
            expect(output).to include("Devise")
            expect(output).to include("User")
            expect(output).to include("database_authenticatable")
          end

          it "renders Rails 8 built-in auth" do
            ctx = { auth: { authentication: { rails_auth: true }, authorization: {} } }
            output = described_class.new(ctx).call
            expect(output).to include("Rails 8 built-in auth")
          end

          it "renders has_secure_password models" do
            ctx = { auth: { authentication: { has_secure_password: [ "User" ] }, authorization: {} } }
            output = described_class.new(ctx).call
            expect(output).to include("has_secure_password")
            expect(output).to include("User")
          end

          it "renders Pundit policies" do
            ctx = { auth: { authentication: {}, authorization: { pundit: [ "UserPolicy" ] } } }
            output = described_class.new(ctx).call
            expect(output).to include("Pundit")
            expect(output).to include("UserPolicy")
          end

          it "renders CanCanCan" do
            ctx = { auth: { authentication: {}, authorization: { cancancan: true } } }
            output = described_class.new(ctx).call
            expect(output).to include("CanCanCan")
          end
        end

        # ---------------------------------------------------------------------------
        # TurboFormatter
        # ---------------------------------------------------------------------------
        describe TurboFormatter do
          it "returns nil when no turbo key in context" do
            expect(described_class.new({}).call).to be_nil
          end

          it "returns nil when turbo has an error" do
            expect(described_class.new({ turbo: { error: "failed" } }).call).to be_nil
          end

          it "returns nil when all turbo sections are empty" do
            ctx = { turbo: { turbo_frames: [], turbo_streams: [], model_broadcasts: [] } }
            expect(described_class.new(ctx).call).to be_nil
          end

          it "renders turbo frames" do
            ctx = { turbo: { turbo_frames: [ { id: "user-list", file: "users/index.html.erb" } ], turbo_streams: [], model_broadcasts: [] } }
            output = described_class.new(ctx).call
            expect(output).to include("Turbo Frames")
            expect(output).to include("user-list")
          end

          it "renders turbo stream templates" do
            ctx = { turbo: { turbo_frames: [], turbo_streams: [ "users/create.turbo_stream.erb" ], model_broadcasts: [] } }
            output = described_class.new(ctx).call
            expect(output).to include("Turbo Stream Templates")
            expect(output).to include("users/create.turbo_stream.erb")
          end

          it "renders model broadcasts" do
            ctx = { turbo: { turbo_frames: [], turbo_streams: [], model_broadcasts: [ { model: "Post", methods: [ "broadcasts_to" ] } ] } }
            output = described_class.new(ctx).call
            expect(output).to include("Model Broadcasts")
            expect(output).to include("Post")
          end
        end

        # ---------------------------------------------------------------------------
        # ViewsFormatter
        # ---------------------------------------------------------------------------
        describe ViewsFormatter do
          it "returns nil when no views key in context" do
            expect(described_class.new({}).call).to be_nil
          end

          it "returns nil when views has an error" do
            expect(described_class.new({ views: { error: "failed" } }).call).to be_nil
          end

          it "renders layouts" do
            ctx = { views: { layouts: [ "application", "admin" ], template_engines: [], templates: {}, helpers: [] } }
            output = described_class.new(ctx).call
            expect(output).to include("Layouts: application, admin")
          end

          it "renders template engines" do
            ctx = { views: { layouts: [], template_engines: [ "erb", "slim" ], templates: {}, helpers: [] } }
            output = described_class.new(ctx).call
            expect(output).to include("Template engines: erb, slim")
          end

          it "renders templates by controller" do
            ctx = { views: { layouts: [], template_engines: [], templates: { "users" => [ "index", "show" ] }, helpers: [] } }
            output = described_class.new(ctx).call
            expect(output).to include("Templates by controller")
            expect(output).to include("`users/`: index, show")
          end

          it "renders helpers" do
            ctx = { views: { layouts: [], template_engines: [], templates: {}, helpers: [ { file: "users_helper.rb", methods: [ "avatar_url" ] } ] } }
            output = described_class.new(ctx).call
            expect(output).to include("Helpers")
            expect(output).to include("users_helper.rb")
          end

          it "renders view component count" do
            ctx = { views: { layouts: [], template_engines: [], templates: {}, helpers: [], view_components: [ "UserComponent" ] } }
            output = described_class.new(ctx).call
            expect(output).to include("View components: 1")
          end
        end

        # ---------------------------------------------------------------------------
        # ApiFormatter
        # ---------------------------------------------------------------------------
        describe ApiFormatter do
          it "returns nil when no api key in context" do
            expect(described_class.new({}).call).to be_nil
          end

          it "returns nil when api has an error" do
            expect(described_class.new({ api: { error: "failed" } }).call).to be_nil
          end

          it "renders api-only flag" do
            ctx = { api: { api_only: true, api_versioning: [], serializers: {} } }
            output = described_class.new(ctx).call
            expect(output).to include("API-only mode: true")
          end

          it "renders api versions" do
            ctx = { api: { api_only: false, api_versioning: [ "v1", "v2" ], serializers: {} } }
            output = described_class.new(ctx).call
            expect(output).to include("API versions: v1, v2")
          end

          it "renders jbuilder template count" do
            ctx = { api: { api_only: false, api_versioning: [], serializers: { jbuilder: 5 } } }
            output = described_class.new(ctx).call
            expect(output).to include("Jbuilder templates: 5")
          end

          it "renders serializer class names" do
            ctx = { api: { api_only: false, api_versioning: [], serializers: { serializer_classes: [ "UserSerializer" ] } } }
            output = described_class.new(ctx).call
            expect(output).to include("UserSerializer")
          end

          it "renders GraphQL stats" do
            ctx = { api: { api_only: false, api_versioning: [], serializers: {}, graphql: { types: 10, mutations: 3 } } }
            output = described_class.new(ctx).call
            expect(output).to include("GraphQL")
            expect(output).to include("Types: 10, Mutations: 3")
          end
        end

        # ---------------------------------------------------------------------------
        # MultiDatabaseFormatter
        # ---------------------------------------------------------------------------
        describe MultiDatabaseFormatter do
          it "returns nil when no multi_database key in context" do
            expect(described_class.new({}).call).to be_nil
          end

          it "returns nil when multi_database has an error" do
            expect(described_class.new({ multi_database: { error: "failed" } }).call).to be_nil
          end

          it "returns nil when multi_db is false" do
            expect(described_class.new({ multi_database: { multi_db: false } }).call).to be_nil
          end

          it "renders database list" do
            ctx = {
              multi_database: {
                multi_db: true,
                databases: [ { name: "primary", adapter: "postgresql", replica: false } ],
                model_connections: []
              }
            }
            output = described_class.new(ctx).call
            expect(output).to include("Multi-Database")
            expect(output).to include("primary")
            expect(output).to include("postgresql")
          end

          it "marks replica databases" do
            ctx = {
              multi_database: {
                multi_db: true,
                databases: [ { name: "primary_replica", adapter: "postgresql", replica: true } ],
                model_connections: []
              }
            }
            output = described_class.new(ctx).call
            expect(output).to include("(replica)")
          end

          it "renders model connections" do
            ctx = {
              multi_database: {
                multi_db: true,
                databases: [],
                model_connections: [ { model: "AnimalsBase", connects_to: "animals" } ]
              }
            }
            output = described_class.new(ctx).call
            expect(output).to include("Model Connections")
            expect(output).to include("AnimalsBase")
          end
        end
      end
    end
  end
end
