# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    module Providers
      # Base class for AI assistant provider serializers (Claude, Copilot, Gemini, Codex, Cursor, Windsurf).
      # Shared compact-mode sections: header, stack, models, gems, architecture, MCP guide, commands, footer.
      class BaseProviderSerializer
        attr_reader :context, :config

        # @param context [Hash] Introspection hash from {Introspector#call}.
        # @param config [RailsAiBridge::Configuration] Bridge configuration.
        def initialize(context, config: RailsAiBridge.configuration)
          @context = context
          @config = config
        end

        # Renders the default compact AI context document (newline-joined sections).
        # Enforces {RailsAiBridge::Configuration#claude_max_lines} by trimming with an MCP pointer when exceeded.
        # Subclasses may override entirely or compose with individual `#render_*` helpers.
        #
        # @return [String] Compact markdown body.
        def render_compact
          lines = []
          lines.concat(render_header)
          lines.concat(render_stack_overview)
          lines.concat(render_key_models)
          lines.concat(render_notable_gems)
          lines.concat(render_architecture)
          lines.concat(render_key_considerations)
          lines.concat(Formatters::Providers::McpGuideFormatter.new(context).call.split("\n"))
          lines.concat(render_key_config_files)
          lines.concat(render_commands)
          lines.concat(render_footer)

          # Enforce max lines (config.claude_max_lines is a generic max line setting)
          max = @config.claude_max_lines
          if lines.size > max
            lines = lines.first(max - 2)
            lines << ''
            lines << '_Context trimmed. Use MCP tools for full details._'
          end

          lines.join("\n")
        end

        # Renders the header section of the context file.
        # @return [Array<String>] Lines for the header.
        def render_header
          [
            "# #{context[:app_name]} — AI Context",
            '',
            "> Auto-generated by rails-ai-bridge v#{RailsAiBridge::VERSION}",
            "> Generated: #{context[:generated_at]}",
            "> Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}",
            '',
            "This file provides a high-level overview of this Rails application's",
            'structure, patterns, and conventions. As an AI assistant, use this context',
            'to quickly understand the project and generate idiomatic code that',
            'adheres to its design decisions. For deeper dives, use the live',
            'MCP tools referenced throughout this document.'
          ]
        end

        # Renders the stack overview section.
        # @return [Array<String>] Lines for the stack overview.
        def render_stack_overview
          lines = ['## Stack']

          schema = context[:schema]
          lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables" if schema && !schema[:error]

          models = context[:models]
          lines << "- Models: #{models.size}" if models.is_a?(Hash) && !models[:error]

          line = ContextSummary.routes_stack_line(context)
          lines << line if line

          auth = context[:auth]
          if auth.is_a?(Hash) && !auth[:error]
            parts = []
            parts << 'Devise' if auth.dig(:authentication, :devise)&.any?
            parts << 'Rails 8 auth' if auth.dig(:authentication, :rails_auth)
            parts << 'Pundit' if auth.dig(:authorization, :pundit)&.any?
            parts << 'CanCanCan' if auth.dig(:authorization, :cancancan)
            lines << "- Auth: #{parts.join(' + ')}" if parts.any?
          end

          jobs = context[:jobs]
          if jobs.is_a?(Hash) && !jobs[:error]
            job_count = jobs[:jobs]&.size || 0
            mailer_count = jobs[:mailers]&.size || 0
            channel_count = jobs[:channels]&.size || 0
            parts = []
            parts << "#{job_count} jobs" if job_count.positive?
            parts << "#{mailer_count} mailers" if mailer_count.positive?
            parts << "#{channel_count} channels" if channel_count.positive?
            lines << "- Async: #{parts.join(', ')}" if parts.any?
          end

          migrations = context[:migrations]
          if migrations.is_a?(Hash) && !migrations[:error]
            pending = migrations[:pending]
            lines << "- Migrations: #{migrations[:total]} total, #{pending&.size || 0} pending"
          end

          lines << ''
          lines
        end

        # Renders the key models section.
        # @return [Array<String>] Lines for the key models.
        def render_key_models
          models = context[:models]
          return [] unless models.is_a?(Hash) && !models[:error] && models.any?

          schema_tables = context.dig(:schema, :tables) || {}
          migrations    = context[:migrations]
          max_show = 15

          lines = ['## Key Models',
                   'The following are the most architecturally significant models, ordered by complexity:']
          sorted_names = models.sort_by { |_name, data| -ContextSummary.model_complexity_score(data) }.map(&:first)
          sorted_names.first(max_show).each do |name|
            data = models[name]
            assoc_count = (data[:associations] || []).size
            val_count   = (data[:validations] || []).size
            enum_names  = (data[:enums] || {}).keys
            top_assocs  = (data[:associations] || []).first(3).map { |a| "#{a[:type]} :#{a[:name]}" }.join(', ')
            table_name  = data[:table_name]

            line = "- **#{name}**"
            line += " (#{assoc_count}a, #{val_count}v)" if assoc_count.positive? || val_count.positive?
            line += " [enums: #{enum_names.join(', ')}]" if enum_names.any?

            cols = ContextSummary.top_columns(schema_tables[table_name])
            line += " [cols: #{cols.map { |c| "#{c[:name]}:#{c[:type]}" }.join(', ')}]" if cols.any?

            line += ' [recently migrated]' if table_name && ContextSummary.recently_migrated?(table_name, migrations)
            line += " — #{top_assocs}" if top_assocs.present?
            lines << line
          end
          lines << "- _...#{models.size - max_show} more (use `rails_get_model_details` tool)_" if models.size > max_show
          lines << ''
          lines
        end

        # Renders the notable gems section.
        # @return [Array<String>] Lines for the notable gems.
        def render_notable_gems
          gems = context[:gems]
          return [] unless gems.is_a?(Hash) && !gems[:error]

          notable = gems[:notable_gems] || gems[:notable] || gems[:detected] || []
          return [] if notable.empty?

          lines = ['## Gems', 'Key gems, categorized by their primary function:']
          grouped = notable.group_by { |g| g[:category]&.to_s || 'other' }
          grouped.each do |category, gem_list|
            names = gem_list.map { |g| g[:name] }.join(', ')
            lines << "- **#{category}**: #{names}"
          end
          lines << ''
          lines
        end

        # Renders the architecture section.
        # @return [Array<String>] Lines for the architecture.
        def render_architecture
          conv = context[:conventions]
          return [] unless conv.is_a?(Hash) && !conv[:error]

          arch = conv[:architecture] || []
          patterns = conv[:patterns] || []
          return [] if arch.empty? && patterns.empty?

          lines = ['## Architecture', 'Detected architectural styles and common patterns:']
          arch.each { |p| lines << "- #{p}" }
          patterns.first(8).each { |p| lines << "- #{p}" }
          lines << ''
          lines
        end

        # Renders the key considerations for performance and security.
        # @return [Array<String>] Lines for performance and security considerations.
        def render_key_considerations
          [
            '## Key Considerations',
            '- **Performance:** For large or frequently accessed tables, always consider database performance. Use the `rails_get_schema` tool to verify indexes and be mindful of N+1 queries by using `includes` and other ActiveRecord optimizations.',
            '- **Security:** Treat all user-provided input as untrusted. Always use strong parameters in controllers and be aware of potential security vulnerabilities when using gems like `ransack` or `pg_search`.',
            '- **Data Drift:** This document is a snapshot. For the most up-to-date information, especially regarding schema and routes, use the live MCP tools.',
            '- **MCP Exposure:** The MCP tools are read-only but expose sensitive application structure. Avoid exposing the HTTP transport on untrusted networks.',
            ''
          ]
        end

        # Renders the key configuration files section.
        # @return [Array<String>] Lines for the key config files.
        def render_key_config_files
          conv = context[:conventions]
          return [] unless conv.is_a?(Hash) && !conv[:error]

          config_files = conv[:config_files] || []
          return [] if config_files.empty?

          lines = ['## Key Config Files', 'Core configuration files for this application:']
          config_files.first(5).each { |f| lines << "- `#{f}`" }
          lines << ''
          lines
        end

        # Renders the command reference section.
        # @return [Array<String>] Lines for the commands.
        def render_commands
          [
            '## Commands',
            '- `bin/dev` — start dev server',
            "- `#{ContextSummary.test_command(context)}` — run tests",
            '- `bundle exec rubocop` — run linter',
            '- `rails db:migrate` — run pending migrations',
            ''
          ]
        end

        # Renders the closing rules and regeneration footer.
        # @return [Array<String>] Lines for the rules section and trailing attribution.
        def render_footer
          SharedAssistantGuidance.compact_engineering_rules_footer_lines(context)
        end
      end
    end
  end
end
