# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    module Providers
      # Generates `.claude/rules/` markdown files for Claude Code auto-discovery.
      # Quick-reference lists keep {ClaudeSerializer} output smaller.
      class ClaudeRulesSerializer
        # Max model names listed per semantic tier in `rails-context.md` when {Configuration#context_mode} is `:compact`.
        SEMANTIC_TIER_LIST_CAP = 20

        # @return [Hash] Introspection context passed to serializers.
        attr_reader :context

        # @param context [Hash] Introspection hash from {Introspector#call}.
        def initialize(context)
          @context = context
        end

        # Writes schema, models, and MCP reference files when content changes.
        #
        # @param output_dir [String] Root directory where `.claude/rules` is created.
        ##
        # Write Claude rules Markdown files into the given output directory, updating only files whose generated content changed.
        # @param [String] output_dir - Root directory where the `.claude/rules` files will be created.
        ##
        # Writes Claude rule Markdown files into the given output directory, creating or updating files under ".claude/rules".
        # @param [String] output_dir - Base directory where the ".claude/rules" folder will be created.
        # @return [Hash{Symbol => Array<String>}] A hash with `:written` and `:skipped` arrays of absolute file paths; `:written` lists files that were created or updated, `:skipped` lists files that were left unchanged because their existing content matched the generated content.
        def call(output_dir)
          rules_dir = File.join(output_dir, ".claude", "rules")
          FileUtils.mkdir_p(rules_dir)

          written = []
          skipped = []

          files = {
            "rails-context.md" => render_context_reference,
            "rails-schema.md" => render_schema_reference,
            "rails-models.md" => render_models_reference,
            "rails-mcp-tools.md" => render_mcp_tools_reference
          }

          files.each do |filename, content|
            next unless content

            filepath = File.join(rules_dir, filename)
            if File.exist?(filepath) && File.read(filepath) == content
              skipped << filepath
            else
              File.write(filepath, content)
              written << filepath
            end
          end

          { written: written, skipped: skipped }
        end

        private

        ##
        # Builds a Markdown summary of the application's semantic model context for Claude rules.
        #
        # Includes application metadata, a model classification guide, and model names grouped by semantic tier.
        ##
        # Builds a Markdown summary of the application's Rails semantic context, including app metadata, model classification, grouped model lists, and pointers to schema/model MCP tools.
        # The output is intended for Claude auto-discovery and includes a regeneration note, application info (when present), a tags guide, models grouped by semantic tier, and pointers to schema and model-detail tools.
        # @return [String, nil] The generated Markdown string, or nil when models are missing or contain an error.
        def render_context_reference
          models = context[:models]
          return nil if models.is_a?(Hash) && models[:error]

          models = {} unless models.is_a?(Hash)

          lines = [
            "# Rails semantic context",
            "",
            "Auto-generated by rails-ai-bridge. Regenerate with `rails ai:bridge:claude`.",
            "",
            "## Application",
            ""
          ]
          lines << "- **Name:** #{context[:app_name]}" if context[:app_name].present?
          lines << "- **Rails:** #{context[:rails_version]}" if context[:rails_version].present?
          lines << "- **Ruby:** #{context[:ruby_version]}" if context[:ruby_version].present?
          lines << "- **Environment:** #{context[:environment]}" if context[:environment].present?
          lines << ""

          lines << "## Model classification"
          lines << ""
          lines << "Tags guide AI attention:"
          lines << "- **core_entity** — configured primary domain models (`config.core_models`)"
          lines << "- **pure_join** — `has_many :through` join rows (FKs + timestamps only)"
          lines << "- **rich_join** — through join model with extra payload columns"
          lines << "- **supporting** — typical models, STI, or non-join tables"
          lines << ""

          grouped = group_models_by_semantic_tier(models)
          cap = semantic_tier_names_cap
          %w[core_entity pure_join rich_join supporting].each do |tier|
            names = grouped[tier] || []
            next if names.empty?

            lines << "### #{tier.tr('_', ' ')} (#{names.size})"
            append_tier_model_bullets(lines, names, cap)
            lines << ""
          end

          lines << "## Pointers"
          lines << ""
          lines << "- Schema tables: see `rails-schema.md` in this folder or `rails_get_schema` (MCP)."
          lines << "- Model details: `rails_get_model_details` with `model:\"Name\"`."
          lines.join("\n")
        end

        # @param models [Hash]
        ##
        # Group model names by semantic tier.
        # Skips models whose metadata is a Hash containing `:error`. If a model's `:semantic_tier` is missing, the model is placed under the `"supporting"` tier.
        # @param [Hash{String=>Object}] models - Mapping of model name to metadata (typically a Hash with optional `:semantic_tier` and/or `:error`).
        ##
        # Groups model names by their semantic tier.
        #
        # @param [Hash{String => Hash, String => Object}] models - A mapping from model name to its metadata. Models whose metadata is a Hash containing `:error` are skipped. If a model's metadata does not provide a `:semantic_tier` (or it is blank), the model is placed in the "supporting" tier.
        # @return [Hash{String => Array<String>}] A hash where each key is a semantic tier and each value is an array of model names assigned to that tier.
        def group_models_by_semantic_tier(models)
          models.each_with_object(Hash.new { |h, k| h[k] = [] }) do |(name, data), acc|
            next if data.is_a?(Hash) && data[:error]

            tier = (data.is_a?(Hash) && data[:semantic_tier].presence) || "supporting"
            acc[tier] << name
          end
        end

        # @return [Integer, nil] cap per tier, or +nil+ when all names should be listed (+:full+ context mode).
        def semantic_tier_names_cap
          return nil if RailsAiBridge.configuration.context_mode == :full

          SEMANTIC_TIER_LIST_CAP
        end

        # @param lines [Array<String>]
        # @param names [Array<String>]
        # @param cap [Integer, nil]
        def append_tier_model_bullets(lines, names, cap)
          sorted = names.sort
          if cap.nil?
            sorted.each { |n| lines << "- #{n}" }
            return
          end

          sorted.first(cap).each { |n| lines << "- #{n}" }
          remaining = sorted.size - cap
          return unless remaining.positive?

          lines << "- … +#{remaining} more (use `rails_get_model_details(detail:\"summary\")` for full list)"
        end

        ##
        # Produce a Markdown listing of database tables from the context schema.
        ##
        # Produces a Markdown listing of database tables with column counts and primary keys.
        # @return [String, nil] The Markdown string describing each table as "- name (N cols, pk: key)", or `nil` if the schema is missing, contains an `:error` key, or has no tables.
        def render_schema_reference
          schema = context[:schema]
          return nil unless schema.is_a?(Hash) && !schema[:error]
          tables = schema[:tables] || {}
          return nil if tables.empty?

          lines = [
            "# Database Tables (#{tables.size})",
            "",
            "For full column details, use the `rails_get_schema` MCP tool.",
            "Call with `detail:\"summary\"` first, then `table:\"name\"` for specifics.",
            ""
          ]

          tables.keys.sort.each do |name|
            data = tables[name]
            col_count = data[:columns]&.size || 0
            pk = data[:primary_key] || "id"
            lines << "- #{name} (#{col_count} cols, pk: #{pk})"
          end

          lines.join("\n")
        end

        ##
        # Builds a Markdown index of ActiveRecord models from the introspection `context`.
        # The output includes a header with the model count and a per-model bullet that may
        # show the table name, semantic tier, number of associations, and number of validations.
        ##
        # Builds a Markdown reference listing ActiveRecord models and brief metadata.
        # Produces a document with a header showing the model count, instructions for `rails_get_model_details`, and one bullet per model including optional table name, semantic tier, association count, and validation count.
        # @return [String, nil] The generated Markdown string, or `nil` when models are missing, empty, or the models hash contains an `:error`.
        def render_models_reference
          models = context[:models]
          return nil unless models.is_a?(Hash) && !models[:error]
          return nil if models.empty?

          lines = [
            "# ActiveRecord Models (#{models.size})",
            "",
            "For full details, use `rails_get_model_details` MCP tool.",
            "Call with no args to list all, then `model:\"Name\"` for specifics.",
            ""
          ]

          models.keys.sort.each do |name|
            data = models[name]
            assocs = (data[:associations] || []).size
            vals = (data[:validations] || []).size
            table = data[:table_name]
            tier = data[:semantic_tier]
            line = "- #{name}"
            line += " (table: #{table})" if table
            line += " — tier: #{tier}" if tier.present?
            line += " — #{assocs} assocs, #{vals} validations"
            lines << line
          end

          append_non_ar_models_to_rules(lines, context[:non_ar_models])

          lines.join("\n")
        end


        # Appends a Markdown subsection for {Introspectors::NonArModelsIntrospector} rows to +lines+.
        #
        # @param lines [Array<String>] mutable buffer for {render_models_reference}
        # @param section [Hash, nil] +:non_ar_models+ payload (or +nil+)
        # @return [void]
        def append_non_ar_models_to_rules(lines, section)
          entries = RailsAiBridge::Tools::ModelDetails::NonArModelsAppendix.entries_from(section)
          return if entries.empty?

          lines << ""
          lines << "## Non-ActiveRecord classes (POJO/Service)"
          entries.each do |row|
            name = row[:name] || row["name"]
            path = row[:relative_path] || row["relative_path"]
            tag = row[:tag] || row["tag"] || RailsAiBridge::Tools::ModelDetails::NonArModelsAppendix::DEFAULT_TAG
            lines << "- **[#{tag}]** `#{name}` — `#{path}`"
          end
        end

        # @return [String] MCP tool reference markdown for Claude rules.
        def render_mcp_tools_reference # rubocop:disable Metrics/MethodLength
          lines = [
            "# MCP Tool Reference",
            "",
            "All introspection tools support a `detail` parameter:",
            "- `summary` — names + counts (default limit: 50)",
            "- `standard` — names + key details (default limit: 15, this is the default)",
            "- `full` — everything including indexes, FKs (default limit: 5)",
            "",
            "## rails_get_schema",
            "Params: `table`, `detail`, `limit`, `offset`, `format`",
            "- `rails_get_schema(detail:\"summary\")` — all tables with column counts",
            "- `rails_get_schema(table:\"users\")` — full detail for one table",
            "- `rails_get_schema(detail:\"summary\", limit:20, offset:40)` — paginate",
            "",
            "## rails_get_model_details",
            "Params: `model`, `detail`",
            "- `rails_get_model_details(detail:\"summary\")` — list all model names",
            "- `rails_get_model_details(model:\"User\")` — associations, validations, scopes, enums, callbacks",
            "- `rails_get_model_details(detail:\"full\")` — all models with full association lists",
            "- Plain Ruby classes under app/models (not ActiveRecord) appear in listings as [POJO/Service]; `model:\"Name\"` returns a short file-path summary.",
            "",
            "## rails_get_routes",
            "Params: `controller`, `detail`, `limit`, `offset`",
            "- `rails_get_routes(detail:\"summary\")` — route counts per controller",
            "- `rails_get_routes(controller:\"users\")` — routes for one controller",
            "- `rails_get_routes(detail:\"full\", limit:50)` — full table with route names",
            "",
            "## rails_get_controllers",
            "Params: `controller`, `detail`",
            "- `rails_get_controllers(detail:\"summary\")` — names + action counts",
            "- `rails_get_controllers(controller:\"UsersController\")` — actions, filters, strong params",
            "",
            "## Other tools (no detail param)",
            "- `rails_get_config` — cache store, session, timezone, middleware, initializers",
            "- `rails_get_test_info` — test framework, factories/fixtures, CI config, coverage",
            "- `rails_get_gems` — notable gems categorized by function",
            "- `rails_get_conventions` — architecture patterns, directory structure",
            "- `rails_search_code(pattern:\"regex\", file_type:\"rb\", max_results:20)` — codebase search",
            "",
            "## Workflow",
            "1. Start with `detail:\"summary\"` to understand the landscape",
            "2. Drill into specifics with filters (`table:`, `model:`, `controller:`)",
            "3. Use `detail:\"full\"` only when you need indexes, FKs, constraints",
            "4. Paginate large results with `limit` and `offset`"
          ]

          lines.join("\n")
        end
      end
    end
  end
end
