# frozen_string_literal: true

module RailsAiBridge
  module Serializers
    module Providers
      # Generates GEMINI.md optimized for Gemini.
      # In :compact mode (default), produces ≤150 lines with MCP tool references.
      # In :full mode, delegates to MarkdownSerializer with behavioral rules.
      class GeminiSerializer
        attr_reader :context

        # @param context [Hash] The introspection context.
        # @param config [RailsAiBridge::Configuration] The configuration object.
        def initialize(context, config: RailsAiBridge.configuration)
          @context = context
          @config = config
        end

        # Generates the GEMINI.md content.
        #
        # @return [String] The generated content.
        def call
          if @config.context_mode == :full
            MarkdownSerializer.new(context,
              header_class: Formatters::GeminiHeaderFormatter,
              footer_class: Formatters::GeminiFooterFormatter
            ).call
          else
            render_compact
          end
        end

        private

        # Renders the compact version of the GEMINI.md content.
        #
        # @return [String] The generated content.
        def render_compact
          lines = []
          lines.concat(render_header)
          lines.concat(render_stack_overview)
          lines.concat(render_key_models)
          lines.concat(render_notable_gems)
          lines.concat(render_architecture)
          lines.concat(render_performance_security_baseline)
          lines.concat(Formatters::McpGuideFormatter.new(context).call.split("
"))
          lines.concat(render_conventions)
          lines.concat(render_commands)
          lines.concat(render_footer)

          # Enforce max lines
          max = @config.claude_max_lines
          if lines.size > max
            lines = lines.first(max - 2)
            lines << ""
            lines << "_Context trimmed. Use MCP tools for full details._"
          end

          lines.join("
")
        end

        def render_header
          [
            "# #{context[:app_name]} — AI Context",
            "",
            "> Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}",
            "> Generated by rails-ai-bridge v#{RailsAiBridge::VERSION}",
            ""
          ]
        end

        def render_stack_overview
          lines = [ "## Stack" ]

          schema = context[:schema]
          if schema && !schema[:error]
            lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables"
          end

          models = context[:models]
          if models.is_a?(Hash) && !models[:error]
            lines << "- Models: #{models.size}"
          end

          line = ContextSummary.routes_stack_line(context)
          lines << line if line

          auth = context[:auth]
          if auth.is_a?(Hash) && !auth[:error]
            parts = []
            parts << "Devise" if auth.dig(:authentication, :devise)&.any?
            parts << "Rails 8 auth" if auth.dig(:authentication, :rails_auth)
            parts << "Pundit" if auth.dig(:authorization, :pundit)&.any?
            parts << "CanCanCan" if auth.dig(:authorization, :cancancan)
            lines << "- Auth: #{parts.join(' + ')}" if parts.any?
          end

          jobs = context[:jobs]
          if jobs.is_a?(Hash) && !jobs[:error]
            job_count = jobs[:jobs]&.size || 0
            mailer_count = jobs[:mailers]&.size || 0
            channel_count = jobs[:channels]&.size || 0
            parts = []
            parts << "#{job_count} jobs" if job_count > 0
            parts << "#{mailer_count} mailers" if mailer_count > 0
            parts << "#{channel_count} channels" if channel_count > 0
            lines << "- Async: #{parts.join(', ')}" if parts.any?
          end

          migrations = context[:migrations]
          if migrations.is_a?(Hash) && !migrations[:error]
            pending = migrations[:pending]
            lines << "- Migrations: #{migrations[:total]} total, #{pending&.size || 0} pending"
          end

          lines << ""
          lines
        end

        def render_key_models
          models = context[:models]
          return [] unless models.is_a?(Hash) && !models[:error] && models.any?

          schema_tables = context.dig(:schema, :tables) || {}
          migrations    = context[:migrations]
          max_show = 15

          lines = [ "## Key Models", "The following are the most architecturally significant models, ordered by complexity:" ]
          sorted_names = models.sort_by { |_name, data| -ContextSummary.model_complexity_score(data) }.map(&:first)
          sorted_names.first(max_show).each do |name|
            data = models[name]
            assoc_count = (data[:associations] || []).size
            val_count   = (data[:validations] || []).size
            enum_names  = (data[:enums] || {}).keys
            top_assocs  = (data[:associations] || []).first(3).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
            table_name  = data[:table_name]

            line = "- **#{name}**"
            line += " (#{assoc_count}a, #{val_count}v)" if assoc_count > 0 || val_count > 0
            line += " [enums: #{enum_names.join(', ')}]" if enum_names.any?

            cols = ContextSummary.top_columns(schema_tables[table_name])
            line += " [cols: #{cols.map { |c| "#{c[:name]}:#{c[:type]}" }.join(', ')}]" if cols.any?

            line += " [recently migrated]" if table_name && ContextSummary.recently_migrated?(table_name, migrations)
            line += " — #{top_assocs}" if top_assocs && !top_assocs.empty?
            lines << line
          end
          lines << "- _...#{models.size - max_show} more (use `rails_get_model_details` tool)_" if models.size > max_show
          lines << ""
          lines
        end

        def render_notable_gems
          gems = context[:gems]
          return [] unless gems.is_a?(Hash) && !gems[:error]
          notable = gems[:notable_gems] || gems[:notable] || gems[:detected] || []
          return [] if notable.empty?

          lines = [ "## Gems", "Key gems, categorized by their primary function:" ]
          grouped = notable.group_by { |g| g[:category]&.to_s || "other" }
          grouped.each do |category, gem_list|
            names = gem_list.map { |g| g[:name] }.join(", ")
            lines << "- **#{category}**: #{names}"
          end
          lines << ""
          lines
        end

        def render_architecture
          conv = context[:conventions]
          return [] unless conv.is_a?(Hash) && !conv[:error]

          arch = conv[:architecture] || []
          patterns = conv[:patterns] || []
          return [] if arch.empty? && patterns.empty?

          lines = [ "## Architecture", "Detected architectural styles and common patterns:" ]
          arch.each { |p| lines << "- #{p}" }
          patterns.first(8).each { |p| lines << "- #{p}" }
          lines << ""
          lines
        end

        def render_performance_security_baseline
          ContextSummary.compact_performance_security_section + [ "" ]
        end

        def render_conventions
          conv = context[:conventions]
          return [] unless conv.is_a?(Hash) && !conv[:error]

          config_files = conv[:config_files] || []
          return [] if config_files.empty?

          lines = [ "## Key Config Files", "Core configuration files for this application:" ]
          config_files.first(5).each { |f| lines << "- `#{f}`" }
          lines << ""
          lines
        end

        def render_commands
          [
            "## Commands",
            "- `bin/dev` — start dev server",
            "- `#{ContextSummary.test_command(context)}` — run tests",
            "- `bundle exec rubocop` — run linter",
            "- `rails db:migrate` — run pending migrations",
            ""
          ]
        end

        def render_footer
          [
            "## Rules",
            "- Follow existing patterns and conventions",
            "- Use the MCP tools to check schema before writing migrations",
            "- Match existing code style",
            "- Run tests after changes",
            ""
          ]
        end
      end
    end
  end
end
